version: "3.3"

services:

  homeareainfo:
    image: "beveradb/homeareainfo:latest"
    container_name: "homeareainfo"
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
    volumes:
      - /tmp/hah-datasets:/app/datasets
      - /tmp/hah-caches:/app/caches
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeareainfo.rule=Host(`homearea.info`)"
      - "traefik.http.routers.homeareainfo.entrypoints=websecure"
      - "traefik.http.routers.homeareainfo.tls.certresolver=mytlschallenge"

